### ISSUE TITLE
<nanaimo-city>/<nanaimo-city>.md

### ISSUE THREAD

**Issue by KailsL** [mapnificent/mapnificent_cities#27]
```
---
ityid: nanaimo-city
cityname: Nanaimo
# Center of the map when loaded
# Coordinates as [LNG, LAT] (like GeoJSON, NOT like leaflet)
# (the leading dash is NOT a minus sign, it's a list item)
coordinates:
- 49.160023
- 123.956755
description: ''
# Preferably provide a transitfeeds.com location ID, e.g.
tf_location_ids:
- 169-berlin-germany
# Or provide GTFS files like so
gtfs:
  example_feed_name:
    # Transitfeeds.com feed id if available
    tf_feed_id: verkehrsverbund-berlin-brandenburg/213
    # URL of Feed if tf_location_ids or tf_feed_id are not available
    url: https://bctransit.com/servlet/bctransit/data/GTFS%20-%20Nanaimo
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [Transit Agency Name](http://bctransit.com)
([Terms of Use](https://bctransit.com/*/footer/open-data/terms-of-use))
```
