### ISSUE TITLE
Barcelona

### ISSUE THREAD

**Issue by benyscott** [mapnificent/mapnificent_cities#48]
```
---
cityid: barcelona
cityname: Barcelona
# Center of the map when loaded
# Coordinates as [LNG, LAT] (like GeoJSON, NOT like leaflet)
# (the leading dash is NOT a minus sign, it's a list item)
coordinates:
- 41.386930
- 2.170046
description: ''
# Or provide GTFS files like so
gtfs:
  tmb:
    # Transitfeeds.com feed id if available
    tf_feed_id: transports-metropolitans-de-barcelona-tmb/995
    url: http://transitfeeds.com/p/transports-metropolitans-de-barcelona-tmb/995/latest/download
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [TMB](https://www.tmb.cat)
([CC-BY 4.0](http://www.amb.cat/s/es/web/area-metropolitana/dades-obertes/condicions-d-us.html))
```
