### ISSUE TITLE
Renfe Cercanias

### ISSUE THREAD

**Issue by benyscott** [mapnificent/mapnificent_cities#49]
```
---
cityid: renfecercanias
cityname: Renfe Cercanías
# Center of the map when loaded
# Coordinates as [LNG, LAT] (like GeoJSON, NOT like leaflet)
# (the leading dash is NOT a minus sign, it's a list item)
coordinates:
- 40.405638
- -3.689557
description: 'Train networks of the major metropolitan areas of Spain'
# Or provide GTFS files like so
gtfs:
  renfe-cercanias:
    # Transitfeeds.com feed id if available
    tf_feed_id: renfe/1016
    url: http://transitfeeds.com/p/renfe/1016/latest/download
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [Renfe Cercanias](http://www.renfe.com/viajeros/cercanias/index.html)
([License not specified](https://data.renfe.com/dataset/horarios-cercanias/resource/6f1523c6-a9e3-48e3-9ace-bb107a762be6))
```
