### ISSUE TITLE
lecce/lecce.md

### ISSUE THREAD

**Issue by piersoft** [mapnificent/mapnificent_cities#51]
```
---
cityid: Lecce
cityname: Lecce, Italy
# Center of the map when loaded
# Coordinates as [LNG, LAT] (like GeoJSON, NOT like leaflet)
# (the leading dash is NOT a minus sign, it's a list item)
coordinates:
 -18.16946
 - 40.35173
description: ''
# Preferably provide a transitfeeds.com location ID, e.g.
tf_location_ids:
- 104-lecce-italy
# Or provide GTFS files like so
gtfs:
  example_feed_name:
    # Transitfeeds.com feed id if available
    tf_feed_id: sgmspa/104
    url: http://dati.comune.lecce.it/trasporti/gtfs/google_transit.zip
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [S.G.M. S.p.A.](http://www.sgmlecce.it)
([CCBY 4.0](http://opendefinition.org/licenses/cc-by/))
```
