### ISSUE TITLE
estonia/estonia.md

### ISSUE THREAD

**Issue by SkafanderO** [mapnificent/mapnificent_cities#57]
```
---
cityid: estonia
cityname: Estonia
# Center of the map when loaded
# Coordinates as [LNG, LAT] (like GeoJSON, NOT like leaflet)
# (the leading dash is NOT a minus sign, it's a list item)
coordinates:
- 25.549579
- 58.882543
description: ' Descriptions of public transport routes, timetables and stopping locations of Estonia '

# Or provide GTFS files like so
gtfs:
  example_feed_name: Transitfeeds.com
    # Transitfeeds.com feed id if available
    tf_feed_id: maanteeamet/510
    url: https://transitfeeds.com/p/maanteeamet/510/latest/download
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [Estonian Transport Administration](https://www.transpordiamet.ee/en)
([Terms of Use](https://web.peatus.ee/tietoja-palvelusta))
```
