### ISSUE TITLE
Add Helsinki

### ISSUE THREAD

**Issue by kinotus** [mapnificent/mapnificent_cities#61]
---
cityid: helsinki
cityname: Helsinki
coordinates:
- 24.9415
- 60.1706
gtfs:
  helsinki_regional_transport:
    tf_feed_id: helsinki-regional-transport/735
    url: https://transitfeeds.com/p/helsinki-regional-transport/735/latest/download
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [Helsinki Region Transport ](https://www.hsl.fi/en)
([CC BY 4.0](https://www.hsl.fi/en/hsl/open-data))

**Comment by kinotus** [comment]
And here's the input as code block:
```
---
cityid: helsinki
cityname: Helsinki
coordinates:
- 24.9415
- 60.1706
gtfs:
  helsinki_regional_transport:
    tf_feed_id: helsinki-regional-transport/735
    url: https://transitfeeds.com/p/helsinki-regional-transport/735/latest/download
version: 1
# Zoom level when loaded
zoom: 12
---

(c) [Helsinki Region Transport ](https://www.hsl.fi/en)
([CC BY 4.0](https://www.hsl.fi/en/hsl/open-data))
```
